criaCartao('<h1>ENTREMET</h1>' ,'','<img class="ilustrativo" src="image copy.png" alt="ilustrativo"> <h1> PREPARO</h1> <br>  <h2> Mousse de limão</h2> <ul class"preparo"><li>1.Aqueça o creme de leite</li>  <li>2.Dissolva a massa de gelatina.</li>  <li>3.Derreta o chocolate e junte ao suco de limão aquecido.</li> <li>4.Misture até ficar homogêneo</li> <li>5.Junte o creme de leite quente</li> <li>6.Esfrie a mistura até 30 graus</li> <li>7.Bata os dois cremes de leite em pico mole</li> <li>8.Incorpore a mousse para finalizar</li> <br> <h2>Creme de limão e manjericão</h2> <li>1.Em uma panela, junte o ovo, o açúcar e o suco de limão</li> <li>2.Cozinhe até 82 graus. Retire do fogo</li> <li>3.Junte a manteiga e as folhas de manjericão e bata com o mixer para finalizar</li> <li>4.Disponha em formas de silicone de meia esfera</li> <br> <h2>Manteiga de cacau amarela</h2> <li>1.Derreta o chocolate e a manteiga de cacau em banho-maria ou no microondas</li> <li>2.Junte o corante em pó. Bata com o mixer</li> <li>3.Aplique a manteiga de cacau a 30 graus</li> </ul><br> <br>  <h1> INGREDIENTES</h1> <br> <ul class "ingredientes">  <h2> Mousse de limão</h2> <li>1. 200 ml de creme de leite fresco</li>  <li>2. 80 ml de suco de limão taiti</li>  <li>3. 120 g de chocolate branco</li> <li>4. 30 g de massa de gelatina</li>  <br> <h2>Creme de limão e manjericão</h2> <li>1. 155 ml de ovo inteiro</li> <li>2. 30 g de manjericão</li> <li>3. 200 g de açúcar</li> <li>4. 180 ml de suco de limão taiti</li> <li>5. 250 g de manteiga</li> <br> <h2>Manteiga de cacau amarela</h2> <li>1. 100 g de chocolate branco 32%</li> <li>2. 100 g de manteiga de cacau</li> <li>3. 10 g de corante amarelo lipossolúvel em pó</li>  </ul>' )

criaCartao('classe' ,'pergunta ou o que tu quiser falar','<ul><li></li>sssss</ul>ssssssssssssssssssssssssssssssssssssss' )

criaCartao('classe' ,'pergunta ou o que tu quiser falar','sssssssssssssssssssssssssssssssa<br>sssssssssssssssssssssssssssssss' )

criaCartao('classe' ,'pergunta ou o que tu quiser falar','sssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss' )

criaCartao('classe' ,'pergunta ou o que tu quiser falar','sssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss' )

